---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flaky-service
  namespace: {{ namespace }}
  labels:
    team: {{ namespace }}
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: false
  envFrom:
    - secret: flaky-service-unleash-api-token
  accessPolicy:
    outbound:
      external:
        - host: nais-demo-unleash-api.nav.cloud.nais.io
  liveness:
    path: /healthz
  readiness:
    path: /healthz
  resources:
    limits:
      memory: 56Mi
    requests:
      memory: 24Mi
      cpu: 10m
  replicas:
    max: 1
    min: 1
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}