---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: flaky-service
  namespace: {{ namespace }}
  labels:
    team: {{ namespace }}
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: false
  envFrom:
    - secret: flaky-service-unleash-api-token
  env:
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "true"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON
  accessPolicy:
    outbound:
      external:
        - host: nais-demo-unleash-api.nav.cloud.nais.io
    inbound:
      rules:
        - application: flaky-frontend
  liveness:
    path: /healthz
  readiness:
    path: /healthz
  resources:
    limits:
      memory: 56Mi
    requests:
      memory: 24Mi
      cpu: 10m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: sdk
  replicas:
    max: 1
    min: 1
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
