apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: flaky-service
  namespace: examples
  labels:
    team: examples
spec:
    unleashInstance:
      apiVersion: unleash.nais.io/v1
      kind: RemoteUnleash
      name: nais-demo
    secretName: flaky-service-unleash-api-token
    environment: development
