apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "swag-shop"
  namespace: "frontendplattform"
  labels:
    "team": "frontendplattform"
  annotations:
    "nais.io/run-as-group": "65532"
    "nais.io/run-as-user": "65532"
spec:
  image: {{image}}
  port: 3000
  env:
    - name: "NODE_ENV"
      value: "production"
    - name: "NEXT_TELEMETRY_DISABLED"
      value: "1"
    - name: "BACKEND_API_URL"
      value: "http://shop-backend"
    - name: OTEL_METRICS_EXPORTER
      value: prometheus
    - name: OTEL_LOGS_EXPORTER
      value: none
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "false"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector:4317"
    #- name: NODE_OPTIONS
    #  value: "--require @opentelemetry/auto-instrumentations-node/register"
  liveness:
    path: "/"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/"
    port: 3000
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  ttl: 24h
  prometheus:
    enabled: false
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  accessPolicy:
    outbound:
      rules:
        - application: shop-backend
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
