version: 2
updates:
  # github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  # docker
  - package-ecosystem: "docker"
    directory: "/shop-backend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/sentiment-api"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/swag-shop"
    schedule:
      interval: "monthly"
  # gradle
  - package-ecosystem: "gradle"
    directory: "/sentiment-api"
    schedule:
      interval: "monthly"
    groups:
      sentiment-api-gradle:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/shop-backend"
    schedule:
      interval: "monthly"
    groups:
      shop-backend-gradle:
        patterns:
          - "*"
  # npm
  - package-ecosystem: "npm"
    directory: "/swag-shop"
    schedule:
      interval: "monthly"
    groups:
      swag-shop-npm:
        patterns:
          - "*"
