version: 2
updates:
  # github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
  # docker
  - package-ecosystem: "docker"
    directory: "/quotes-backend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/quotes-frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "docker"
    directory: "/quotes-loadgen"
    schedule:
      interval: "monthly"
  # gradle
  - package-ecosystem: "gradle"
    directory: "/quotes-backend"
    schedule:
      interval: "monthly"
    groups:
      quotes-backend-gradle:
        patterns:
          - "*"
  # npm
  - package-ecosystem: "npm"
    directory: "/quotes-frontend"
    schedule:
      interval: "monthly"
    groups:
      quotes-frontend-npm:
        patterns:
          - "*"
  # gomod
  - package-ecosystem: "gomod"
    directory: "/quotes-loadgen"
    schedule:
      interval: "monthly"
