apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "swag-shop"
  namespace: "frontendplattform"
  labels:
    "team": "frontendplattform"
  annotations:
    "start.nais.io/created-by": "Hans Kristian Flaatten"
    "start.nais.io/creationTimestamp": "2023-06-01T05:35:11.960109347"
spec:
  image: {{image}}
  port: 3000
  liveness:
    path: "/"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/"
    port: 3000
    initialDelay: 20
    timeout: 60
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
