AAD_ISSUER_URI: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          #The client_id of this application
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}
      client:
        registration:
          example-clientcredentials:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            scope: api://a1fd9dc1-2590-4e10-86a1-bc611c96dc17/.default
        provider:
          aad:
            token-uri: ${AAD_ISSUER_URI}/oauth2/v2.0/token
            jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys

clients.example-clientcredentials.url: http://localhost:1111

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
