AAD_ISSUER_URI: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851
AZURE_APP_CLIENT_ID: a1fd9dc1-2590-4e10-86a1-bc611c96dc17

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AAD_ISSUER_URI}/v2.0
          #The client_id of this application
          accepted-audience: ${AZURE_APP_CLIENT_ID}, api://${AZURE_APP_CLIENT_ID}

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
