namespace: plattformsikkerhet
team: plattformsikkerhet
ingresses:
  - https://debug-dings.prod-gcp.nais.io
env:
  - name: APPLICATION_PROFILE
    value: PROD
  - name: APPLICATION_REDIRECT_URL
    value: "https://debug-dings.prod-gcp.nais.io/oauth"
  - name: IDPORTEN_WELL_KNOWN_URL
    value: "https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration"
  - name: CLIENT_GCP_AUDIENCE
    value: prod-gcp:plattformsikkerhet:api-dings
  - name: CLIENT_ONPREM_AUDIENCE
    value: prod-fss:plattformsikkerhet:api-dings
  - name: DOWNSTREAM_GCP_API_URL
    value: "https://api-dings.prod-gcp.nais.io/hello"
  - name: DOWNSTREAM_ONPREM_API_URL
    value: "https://api-dings.dev-fss-pub.nais.io/hello"
replicas:
  min: 1
  max: 1
outbound-host:
  - oidc.difi.no
  - api-dings.prod-gcp.nais.io
  - api-dings.prod-fss-pub.nais.io
fss-cluster: prod-fss
