version: '3.1'
services:
  login-aad:
    build: ../oidc-login-azuread/login-proxy-nodejs
    env_file:
      # should contain the secret for AZURE_APP_CLIENT_ID in var AZURE_APP_CLIENT_SECRET
      - secrets/login.env
    environment:
      AZURE_APP_CLIENT_ID: f3912d1f-c317-4dcd-83e8-bdd8fc50753e
      #AZURE_APP_JWKS:
      AZURE_APP_WELL_KNOWN_URL: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
      DOWNSTREAM_API_URL: http://middletier-api:8080/
      DOWNSTREAM_API_CLIENT_ID: 863d14f3-68cb-411b-838f-acbedbbea447
      SESSION_KEY: some-random-key
      AZURE_APP_REDIRECT_URL: http://localhost:3000/oauth2/callback
      AZURE_APP_LOGOUT_REDIRECT_URL: http://localhost:3000/
    ports:
      - 3000:3000
    volumes:
      - ../oidc-login-azuread/login-proxy-nodejs/:/usr/src/app
