AAD_ISSUER_URI: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/

spring:
  security:
    oauth2:
      client:
        registration:
          aad:
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid, ${AZURE_APP_CLIENT_ID}/.default
          api-1:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: api://a1fd9dc1-2590-4e10-86a1-bc611c96dc17/.default
          api-2:
            provider: aad
            client-id: ${AZURE_APP_CLIENT_ID}
            client-secret: ${AZURE_APP_CLIENT_SECRET}
            authorization-grant-type: urn:ietf:params:oauth:grant-type:jwt-bearer
            scope: api://a1fd9dc1-2590-4e10-86a1-bc611c96dc17/.default
        provider:
          aad:
            authorization-uri: ${AAD_ISSUER_URI}/oauth2/v2.0/authorize
            token-uri: ${AAD_ISSUER_URI}/oauth2/v2.0/token
            jwk-set-uri: ${AAD_ISSUER_URI}/discovery/v2.0/keys
  cloud:
    gateway:
      routes:
        - id: api-1
          uri: http://localhost:1111
          predicates:
            - Path=/api1/**
          filters:
            - OnBehalfOfToken=api-1
            - RemoveRequestHeader=Cookie

logging:
  level:
    org.springframework.security: debug
    no.nav: debug

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
