ingresses:
  - https://frontend-dings.dev.nav.no
host:
  - api-dings.dev-fss-pub.nais.io
fss-cluster: dev-fss
env:
  NODE_ENV: production
  API_DINGS_AUDIENCE: dev-fss:plattformsikkerhet:api-dings
  API_DINGS_URL: https://api-dings.dev-fss-pub.nais.io
slack_alert_channel: "plattformsikkerhet-alerts-dev"
