---
apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: plattformsikkerhet
  name: frontend-dings-redis
  namespace: plattformsikkerhet
spec:
  image: bitnami/redis:5.0.9
  port: 6379
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    port: 6379
    protocol: redis
  accessPolicy:
    inbound:
      rules:
        - application: frontend-dings
  envFrom:
    - secret: redis-password
