name: main

on:
  push:
    branches:
      - main
env:
  APP: frontend-dings
  TEAM: plattformsikkerhet
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: actions/checkout@v1
        name: Checkout code
      - name: Cache node deps
        id: cache-node
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: install deps
        run: npm install
      - name: build client
        run: npm run build-client
      - name: build server
        run: npm run build-server
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build an push the Docker image
        run: |
          npm prune --production
          docker build --pull --tag ${IMAGE} .
          docker push ${IMAGE}

  deploy-dev-gcp:
    name: Deploy to dev-gcp
    needs: build
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: dev-gcp
            RESOURCE: .nais/nais.yml,.nais/redis.yml
            VARS: .nais/dev.yml

  deploy-prod-gcp:
    name: Deploy to prod-gcp
    needs: build
    if: "github.ref == 'refs/heads/main'"
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: prod-gcp
            RESOURCE: .nais/nais.yml,.nais/redis.yml
            VARS: .nais/prod.yml
