AZURE_APP_TENANT_ID: 966ac572-f5b7-4bbe-aa88-c76419c0f851
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:  https://login.microsoftonline.com/${AZURE_APP_TENANT_ID}/oauth2/v2.0/token

no.nav.security.jwt:
  client:
    registration:
      example-clientcredentials:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://a1fd9dc1-2590-4e10-86a1-bc611c96dc17/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

downstream:
  resource:
    url: http://localhost:1111/

logging.level.org.springframework: INFO
logging.level.no.nav: DEBUG

server:
  error:
    include-stacktrace: never

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
