apiVersion: nais.io/v1
kind: Application
metadata:
  name: quotes-loadgen
spec:
  image: "ghcr.io/nais/examples/quotes-loadgen:latest"
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  liveness:
    path: /healthz
    initialDelay: 20
    periodSeconds: 10
  readiness:
    path: /readyz
    initialDelay: 10
    periodSeconds: 5
  accessPolicy:
    inbound:
      rules: []
    outbound:
      rules:
        - application: quotes-frontend
  env:
    - name: LOG_LEVEL
      value: "info"
