apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "quotes-frontend"
  namespace: "examples"
  labels:
    "team": "examples"
  annotations:
    "nais.io/run-as-group": "65532"
    "nais.io/run-as-user": "65532"
spec:
  image: {{image}}
  port: 3000
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
  env:
    - name: "NODE_ENV"
      value: "production"
    - name: "NEXT_TELEMETRY_DISABLED"
      value: "1"
    - name: "NEXT_PUBLIC_BACKEND_URL"
      value: "http://quotes-backend"
    - name: "ANALYTICS_SERVICE_URL"
      value: "http://quotes-analytics:8081"
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: none
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_METRICS_ENABLED
      value: "true"
    - name: OTEL_METRICS_EXEMPLAR_FILTER
      value: ALWAYS_ON
  liveness:
    path: "/"
    port: 3000
    initialDelay: 20
    timeout: 60
  readiness:
    path: "/"
    port: 3000
    initialDelay: 20
    timeout: 60
  replicas:
    min: 1
    max: 1
  prometheus:
    enabled: false
    path: "/metrics"
  resources:
    limits:
      memory: "128Mi"
    requests:
      cpu: "100m"
      memory: "56Mi"
  accessPolicy:
    outbound:
      rules:
        - application: quotes-backend
        - application: quotes-analytics
  filesFrom:
    - emptyDir:
        medium: Memory
      mountPath: /app/.next/cache
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
