apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: quotes-frontend
  namespace: {{ namespace }}
  labels:
    team: {{ namespace }}
spec:
    unleashInstance:
      apiVersion: unleash.nais.io/v1
      kind: RemoteUnleash
      name: nais-demo
    secretName: quotes-frontend-unleash-api-token
    environment: development
