name: quotes-loadgen

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/quotes-loadgen.yaml
      - .github/workflows/service-pipeline.yaml
      - quotes-loadgen/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/quotes-loadgen.yaml
      - .github/workflows/service-pipeline.yaml
      - quotes-loadgen/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pipeline:
    uses: ./.github/workflows/service-pipeline.yaml
    with:
      service-name: quotes-loadgen
      service-path: ./quotes-loadgen
      enable-tests: true
      enable-coverage: false
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
